site_name: Helpmonks Developer Guides
theme_dir: readthedocshm
site_url: http://developer.helpmonks.com
site_description: These are the Helpmonks developer documentation pages
site_author: Nitai Aventaggiato
markdown_extensions:
  - smarty
  - toc
extra:
  version: 1.0
pages:
- 'Home': 'index.md'
- 'Developer API': 
  - 'Getting Started':
    - 'Overview': 'api/overview.md'
    - 'Authentication': 'api/authentication.md'
    - 'Query Syntax': 'api/syntax.md'
  - 'APIs':
    - 'Conversation':
      - 'Find': 'api/conversation/find.md'
    - 'Customer':
      - 'Find' : 'api/customer/find.md'
    - 'Mailbox':
      - 'Find': 'api/mailbox/find.md'
    - 'Label':
      - 'Find': 'api/label/find.md'
    - 'User':
      - 'Find': 'api/user/find.md'
    - 'Search':
      - 'Find': 'api/search/index.md'
  - 'Data Models':
    - 'Conversations' : 'api/models/conversation.md'
    - 'Customer' : 'api/models/customer.md'
    - 'Mailbox' : 'api/models/mailbox.md'
    - 'Label' : 'api/models/label.md'
    - 'User' : 'api/models/user.md'
- 'About': 'about.md' 