site_name: Helpmonks Developer Guides
theme:
  name: material
  custom_dir: theme_hm
  palette:
    primary: 'light green'
    accent: 'light green'
  logo: 'images/icon_transparent_128.png'
  features:
    - tabs
site_url: http://developer.helpmonks.com
site_description: The Helpmonks developer documentation pages
site_author: Nitai Aventaggiato
markdown_extensions:
  - smarty
  - toc
extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/helpmonks'
nav:
- 'Home': 'index.md'
- 'Developer API':
  - 'Getting Started':
    - 'Overview': 'api/overview.md'
    - 'Authentication': 'api/authentication.md'
    - 'Query Syntax': 'api/syntax.md'
  - 'APIs':
    - 'Conversation':
      - 'Find': 'api/conversation/find.md'
      - 'FindOne': 'api/conversation/findone.md'
      - 'FindById': 'api/conversation/findbyid.md'
      - 'Update': 'api/conversation/update.md'
      - 'Update Status': 'api/conversation/update_status.md'
      - 'Update Assignee': 'api/conversation/update_assignee.md'
      - 'Update Label': 'api/conversation/update_label.md'
      - 'Add Notes': 'api/conversation/note_add.md'
      - 'Delete Note': 'api/conversation/note_delete.md'
      - 'Delete': 'api/conversation/delete.md'
      - 'Create': 'api/conversation/create.md'
    - 'Customer':
      - 'Find' : 'api/customer/find.md'
      - 'FindOne': 'api/customer/findone.md'
      - 'FindById': 'api/customer/findbyid.md'
      - 'Delete': 'api/customer/delete.md'
      - 'Update': 'api/customer/update.md'
      - 'Update Label': 'api/customer/update_label.md'
      - 'Create': 'api/customer/create.md'
    - 'Mailbox':
      - 'Find': 'api/mailbox/find.md'
      - 'FindOne': 'api/mailbox/findone.md'
      - 'FindById': 'api/mailbox/findbyid.md'
      - 'Create': 'api/mailbox/create.md'
    - 'Label':
      - 'Find': 'api/label/find.md'
      - 'FindOne': 'api/label/findone.md'
      - 'FindById': 'api/label/findbyid.md'
    - 'User':
      - 'Find': 'api/user/find.md'
      - 'FindOne': 'api/user/findone.md'
      - 'FindById': 'api/user/findbyid.md'
      - 'Delete': 'api/user/delete.md'
      - 'Update': 'api/user/update.md'
      - 'Create': 'api/user/create.md'
      - 'Activate': 'api/user/activate.md'
      - 'Deactivate': 'api/user/deactivate.md'
    - 'Search': 'api/search/index.md'
  - 'Data Models':
    - 'Conversations' : 'api/models/conversation.md'
    - 'Customer' : 'api/models/customer.md'
    - 'Mailbox' : 'api/models/mailbox.md'
    - 'Label' : 'api/models/label.md'
    - 'User' : 'api/models/user.md'
- 'About Helpmonks': 'about.md'
- 'Single-Sign-On (SAML)':
  - 'Introduction' : 'saml/introduction.md'
  - 'SAML Setup' : 'saml/setup.md'
  - 'SAML Settings' : 'saml/settings.md'
  - 'Auth0 Example' : 'saml/example_auth0.md'
  - 'OneLogin Example' : 'saml/example_onelogin.md'
- 'Single-Sign-On (oAuth)':
  - 'Introduction' : 'sso/introduction.md'
  - 'Authentication' : 'sso/authentication.md'
  - 'SSO API' :
    - 'Create Token' : 'sso/token_create.md'
    - 'Update Token' : 'sso/token_update.md'
    - 'Get Token' : 'sso/token_get.md'
    - 'Check Token' : 'sso/token_check.md'
    - 'Delete Token' : 'sso/token_delete.md'
  - 'SSO Login' : 'sso/login.md'
  - 'Manage Access Tokens' : 'sso/access_token.md'